version: '2'

services:
  jira:
    image: blacklabelops/jira
    container_name: jirasoftware
    networks:
      - jiranet
    volumes:
      - jiradata:/var/atlassian/jira
    ports:
      - '80:8080'
    environment:
      - 'JIRA_DATABASE_URL=postgresql://jira@postgresql/jiradb'
      - 'JIRA_DB_PASSWORD=jellyfish'
      - 'CATALINA_OPTS= -Xms256m -Xmx1g'
      - 'JIRA_PROXY_NAME='
      - 'JIRA_PROXY_PORT='
      - 'JIRA_PROXY_SCHEME='
      - 'DOCKER_WAIT_HOST=postgresql'
      - 'DOCKER_WAIT_PORT=5432'
    links:
      - 'postgresql:postgresql'
    labels:
      com.blacklabelops.description: "Atlassian Jira"
      com.blacklabelops.service: "jira"

  postgresql:
    image: blacklabelops/postgres
    hostname: postgresql
    networks:
      - jiranet
    volumes:
      - postgresqldata:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_USER=jira'
      # CHANGE THE PASSWORD!
      - 'POSTGRES_PASSWORD=jellyfish'
      - 'POSTGRES_DB=jiradb'
      - 'POSTGRES_ENCODING=UNICODE'
      - 'POSTGRES_COLLATE=C'
      - 'POSTGRES_COLLATE_TYPE=C'
    labels:
      com.blacklabelops.description: "PostgreSQL Database Server"
      com.blacklabelops.service: "postgresql"

volumes:
  jiradata:
    external: false
  postgresqldata:
    external: false

networks:
  jiranet:
    driver: bridge
