jira:
  image: teamatldocker/jira
  container_name: jira
  ports:
    - '80:8080'
  environment:
    - 'JIRA_DATABASE_URL=mysql://jiradb@mysql/jiradb'
    - 'JIRA_DB_PASSWORD=jellyfish'
  links:
    - 'mysql:mysql'
mysql:
  image: mysql:5.6
  environment:
    - 'MYSQL_ROOT_PASSWORD=verybigsecretrootpassword'
    - 'MYSQL_DATABASE=jiradb'
    - 'MYSQL_USER=jiradb'
    - 'MYSQL_PASSWORD=jellyfish'
