version: 2
jobs:
  build_branch:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip \
              curl \
              curl-dev
      - run:
          name: Build Branch Images
          command: |
            set +o pipefail
            bash buildscripts/buildDevelopmentImages.sh
      - run:
          name: Test Branch Images
          command: |
            bash buildscripts/testDevelopmentImages.sh

  build_releases:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip \
              curl \
              curl-dev
      - run:
          name: Build Docker Release Images
          command: |
            set +o pipefail
            bash buildscripts/buildSupportedJiraImages.sh
      - run:
          name: Test Docker Release Images
          command: |
            bash buildscripts/testSupportedJiraImages.sh
      - run:
          name: Push Dockerhub Release Images
          command: |
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
            bash buildscripts/releaseSupportedJiraImages.sh

workflows:
  version: 2
  build_pipeline:
    jobs:
      - build_releases:
          filters:
            branches:
              only: master
      - build_branch:
          filters:
            branches:
              ignore:
                - master
  nightly:
    triggers:
      - schedule:
          cron: "0 1 * * 1"
          filters:
            branches:
              only:
                - master
    jobs:
      - build_releases
