version: 2
jobs:
  build_branch:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip \
              curl \
              curl-dev
            pip install \
              docker-compose
      - run:
          name: Build Branch Images
          command: |
            set +o pipefail
            sh buildscripts/buildDevelopmentImages.sh
      - run:
          name: Test Branch Images
          command: |
              sh buildscripts/testDevelopmentImages.sh

  build_development:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip \
              curl \
              curl-dev
            pip install \
              docker-compose
      - run:
          name: Build Development Images
          command: |
            set +o pipefail
            sh buildscripts/buildDevelopmentImages.sh
      - run:
          name: Test Development Images
          command: |
              sh buildscripts/testDevelopmentImages.sh
      - run:
          name: Push Dockerhub Development Images
          command: |
              docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
              sh buildscripts/releaseDevelopmentImages.sh

  build_releases:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip \
              curl \
              curl-dev
            pip install \
              docker-compose
      - run:
          name: Build Docker Release Images
          command: |
            set +o pipefail
            sh buildscripts/buildSupportedJiraImages.sh
      - run:
          name: Test Docker Release Images
          command: |
            sh buildscripts/testSupportedJiraImages.sh
      - run:
          name: Push Dockerhub Release Images
          command: |
              docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
              sh buildscripts/releaseSupportedJiraImages.sh

workflows:
  version: 2
  build_pipeline:
    jobs:
      - build_releases:
          filters:
            branches:
              only: master
      - build_development:
          filters:
            branches:
              only: dev
      - build_branch:
          filters:
            branches:
              ignore:
                - dev
                - master
